In [ ]:
import numpy as np

def get_matrix(rows, cols):
    matrix = []
    for i in range(rows):
        row_data = []
        for j in range(cols):
            value = int(input(f"Enter the value for ({i+1},{j+1}): "))
            row_data.append(value)
        matrix.append(row_data)
    return np.array(matrix)

In [ ]:
try:
    row = int(input("Enter the number of rows for the first matrix: "))
    col = int(input("Enter the number of columns for the first matrix: "))
    row2 = int(input("Enter the number of rows for the second matrix: "))
    col2 = int(input("Enter the number of columns for the second matrix: "))
        
    print("\nEnter values for the first matrix:")
    matrix1 = get_matrix(row, col)
    
    print("\nEnter values for the second matrix:")
    matrix2 = get_matrix(row2, col2)

    print("\nFirst matrix:")
    print(matrix1)

    print("\nSecond matrix:")
    print(matrix2)

    print("Which operation do you wish to do:")
    print("1. Cross product")
    print("2. Dot product")
    print("3. Matrix multiplication(eg. (3 x 3) x (3 x n)")
    choice = int(input("Enter your choice: "))

    if choice == 1:
        if matrix1.shape == (3,) and matrix2.shape == (3,):
            print("Cross product:")
            print(np.cross(matrix1, matrix2))
        else:
            raise ValueError("Cross product is only defined for 3-element vectors.")
    elif choice == 2:
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("Dot product: matrix1 columns must equal matrix2 rows.")
        print("Dot product:")
        print(np.dot(matrix1, matrix2))
    elif choice == 3:
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("Matrix multiplication: matrix1 columns must equal matrix2 rows.")
        print("Matrix multiplication:")
        print(np.matmul(matrix1, matrix2))
    else:
        print("Invalid choice.")

except Exception as e:
    print(f"An error occurred: {e}")

Enter the number of rows for the first matrix:  3
Enter the number of columns for the first matrix:  3
Enter the number of rows for the second matrix:  3
Enter the number of columns for the second matrix:  2



Enter values for the first matrix:


Enter the value for (1,1):  1
Enter the value for (1,2):  2
Enter the value for (1,3):  3
Enter the value for (2,1):  4
Enter the value for (2,2):  5
Enter the value for (2,3):  6
Enter the value for (3,1):  7
Enter the value for (3,2):  8
Enter the value for (3,3):  9



Enter values for the second matrix:


Enter the value for (1,1):  1
Enter the value for (1,2):  2
Enter the value for (2,1):  3
Enter the value for (2,2):  4
Enter the value for (3,1):  5
Enter the value for (3,2):  6



First matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Second matrix:
[[1 2]
 [3 4]
 [5 6]]
Which operation do you wish to do:
1. Cross product
2. Dot product
3. Matrix multiplication


Enter your choice:  3


Matrix multiplication:
[[ 22  28]
 [ 49  64]
 [ 76 100]]
